# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_NPY=111  CONDA_PY=27
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "YRp/LclDVFWtsksKP0jUPe9qo2q2dWz3EUR1X+b9zPE6QRtCI/Rp5i7dyAD0HthnsS9A9fmxL2cyG/liJ3S2g9/irZSmcLO+FUrD61TZHfXxjprEN0fXTHA79ZQcnJCqPAlVGOQMvnZsvJdF069QZQkTm8mvLERjbwX5b2GnwMCrhFwts6kRFTTz5vaRw3oy3VECxT0INNoG3sDKd1dFRxn62sCbWMq0GsMbmzJGT9ZIwfzaibgk4yAMWc8CL5E3P7rvqXVoocfuEwKmbXRo6QBicsWV3RcCNjQMtaU3i+C8OY5CpwUt0zqo8N9nzO7KH+SyUSVPN9El7ZMj/5KnzAgghcJYhkpgrCkF7IihI7S4J0bpMpmvBL+EA0iFECHIITbkMT7bEIzMl9ANtXCdquXSw2QJgwag+jiANmyzGNK9L/JNWHeV8AaCbgJ24/5Z1ciLLZ7+lRc4DYq6OvGVoU/bmzncG+e4Req/ancEcLkE4iUQgoMKQ8H7Y5lkinOIwYZDFeCC4hK0HcoThqs+11jYEIgfndD95U6C9EPHVzAWb65xJ7ADcKPY7kaoGCGJruWbA7chfSFQrsr+8eeuPKFMZbSEaQT5SEuUfH7HIPEBOSiYEaxnIdoO936by1z5WoUJ1ygOZmWZo60REu7TUywfGk8NVZ3yJy06R9i8YVA="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
