travis:
  secure:
    BINSTAR_TOKEN: icQHW+jghoPMjYCA6sCzrM1+i8ez143HTaIbgfTe7i7+YdCJWxoATiOiFTcVUv6JvfB56AQt2xgu4BomZ75P6tVjSwhda2DhQRruz1jJqeauUHTU2S8CIhXI5GH70GkYyvAOWtaw3EPRsgy5wwqJSdykDk/3FCCcdrY48VHjOcn5QGTcudB5ZFzFJZ7aJiEIpK2D4/NMyXa5pR2AdwJkBO2jMlHrNL56kSBCzezLOgXPEHcdDah6gGX4JYWQmm5iv4Kv5HugkafCYBjLvkPpUz52CZilkNjtbskojnmgeig5hjxQHnov5/Lj8A6QK1OSNCWETgOLFhtaSuzCfk+2uyW0Beko0A/66eK3Axui5ccNj23e8bG8yJiph94y5gTyuJbsYawt4ttKjErViDfJ+oyNkcInakMmxVk1M81b7Cj0BrD2cW1cHz2EuvDBYeP/TQJkghbVtckFXB9dNIBgzEOCvwuEKxEKCoPhxRWs5xnOfya8sg4zemhozkwotsoGLSCjPihF3KAww7ry9u7KCbxWiUlCRAXZBMUC9XQ3SwB10d/qVNFOYueMQdtgTDzXmvq1eyW5lv3q1hdQmOWYhp2SyudwnmiYitjBi0Yr55SbVOC5SytElYhplQfyl5BvzstFjuPfUmbdWtxlQHKSpdJClZNYfE4ABAdAK2EKwkE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
