travis:
  secure:
    BINSTAR_TOKEN: fYWIKZUOqvUcCKqNUtXF8RYV51oJY00XZhoKHILHX2zr5YJ4ZxcWc2uaZEmg5l1hM5z62jAjx4p3HTtmkfK2gVpjsA94UoclSAU/c+blvOQpZdeAsxLZt2gEA0IV5XSDLUtjHCejN6O0WhYjMtKwhM6nrEILQmsX80duGRNvSJo69g/oSBUq3aLs4pem9fjHZIDOFhSgdason8jKhjNKVhW6z6yoklj9yBIFwna7E/Fc0TTdsPVysJaWZ1v62d+gUCD1oWt02uqCCzkduscegZfktLDtCSlKkdi9gf+UTmQrj0GKMBsToQef9wfCMwgl9nO68Vkc+DfRdKIJNEiLgJ/bCqI8vS1QBF4N7V8Kv3nhHtir9CNP3FYTZOrbtFPP0hVTFsJNG44RVioFmmOFeoYASaS3P66tIhr19+q7PdHHKuzpTgpm5V7NFLa/3GoVOaH2zkBfS3VnynN3dFCUL7Hf3bcGmF11SSkeji6Nw0H/bMYq9HgArJAkXuV1QUZ0BxPqLhCAKm/olYVXYNqI/juvIbODlGZX1z/kvYpPrXzLmRkyXWQZeSEXM0XjXifpcrGhNsOKnQw/jQ3wHANgUFLZVnpQYhLFXbOkQmpTnaGnMON81zsXpF20FpOSbEsOx40VymARq03swOO46+LUhHP1gqt8M41haLKg/RPiJUA=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
